// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hypuacrfmfdwxojelbqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5cHVhY3JmbWZkd3hvamVsYnFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTQ3NDIsImV4cCI6MjA2OTYzMDc0Mn0.RPi0cWtLaBBF96B4R-RdUgQx-zi49vmSzAbb2Cfuy5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});